name: Build and Test

# trigger on any PR or push
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    strategy:
      max-parallel: 4
      matrix:
        platform: [ubuntu-latest]
        python-version: ["3.8", "3.10"]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade wheel build setuptools
          python -m build .
          pip install dist/*.whl
      - name: Test Import
        run: |
          python -c 'import fastmri'

  lint-and-test:
    name: Lint and Test
    strategy:
      max-parallel: 4
      matrix:
        platform: [ubuntu-latest]
        python-version: ["3.8", "3.10"]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade "pip<24.1"
          pip install --upgrade wheel
          pip install --editable ".[tests]"
      - name: Check Formatting and Lint
        run: |
          python --version
          black --version
          black fastmri_examples fastmri tests --check
          mypy --version
          mypy fastmri
          flake8 --version
          flake8 fastmri_examples fastmri tests
          isort --version
          isort --check-only fastmri tests fastmri_examples
      - name: Run pytest
        run: |
          echo -e "PyTorch \c" && pip show torch | grep Version 
          pytest tests
